# Generated by Django 2.2 on 2019-09-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='applicants',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='applicants',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='applicants',
            name='skills',
            field=models.CharField(default='', max_length=200),
        ),
    ]
