# Generated by Django 2.2 on 2019-09-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190904_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='email',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='name',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='phone',
            field=models.FileField(default='', max_length=13, upload_to=''),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='skills',
            field=models.FileField(default='', max_length=200, upload_to=''),
        ),
    ]
