# Generated by Django 2.2 on 2019-09-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190904_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='resume',
            field=models.FileField(upload_to='jobs/pdfs'),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='skills',
            field=models.CharField(max_length=200),
        ),
    ]
