# Generated by Django 2.2 on 2019-09-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer3',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer4',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer5',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
